const badWords = [
  'anal', 'anus', 'arse', 'arsehole', 'ass', 'assbag', 'assbandit', 'assbang', 'assbanged', 'assbanger',
  'assbite', 'assclown', 'asscock', 'assface', 'assfuck', 'assfucker', 'asshat', 'asshead', 'asshole',
  'asshopper', 'asshore', 'assjacker', 'asskiss', 'asslick', 'asslicker', 'assload', 'assmaster',
  'assmonkey', 'assmunch', 'assmuncher', 'asspirate', 'asspuppet', 'assrammer', 'assranger',
  'assshit', 'assshole', 'asssucker', 'asswad', 'asswipe', 'asswhore',
  'bampot', 'bastard', 'bastards', 'bawsack', 'bellend', 'berk', 'bint', 'bitch', 'bitches', 'bitchin',
  'bitching', 'bitchslap', 'biatch', 'blowjob', 'blowjobs', 'blowme', 'bollocks', 'bollok', 'bollox',
  'boner', 'boob', 'boobs', 'boobies', 'booby', 'brownie', 'brownies', 'bukkake', 'bullshit',
  'bullshits', 'bullshitted', 'bullshitting', 'bum', 'bumboy', 'bumfuck', 'bung', 'bunghole',
  'buttface', 'buttfuck', 'buttfucker', 'butthole', 'buttplug', 'buttwipe',
  'cameltoe', 'carpetmuncher', 'chav', 'chink', 'chinks', 'choad', 'chode', 'clit', 'clitoral',
  'clitoris', 'clits', 'clusterfuck', 'cock', 'cockass', 'cockbite', 'cockblock', 'cockblocker',
  'cockburger', 'cockface', 'cockfucker', 'cockhead', 'cockholster', 'cockjockey', 'cockknob',
  'cockmaster', 'cockmonkey', 'cockmuncher', 'cocknose', 'cocknugget', 'cockqueen', 'cockrider',
  'cockrock', 'cocks', 'cockshit', 'cocksman', 'cocksmith', 'cocksmoker', 'cocksucker',
  'cocksucking', 'cocksuck', 'cockwaffle', 'cockwhore', 'coital', 'condom', 'cooch', 'coochie',
  'coochy', 'coon', 'coons', 'corksucker', 'cornhole', 'crackwhore', 'crap', 'crappy', 'creampie',
  'cripple', 'cum', 'cumbucket', 'cumdumpster', 'cumfest', 'cumfiesta', 'cumming', 'cums', 'cumshot',
  'cumshots', 'cumslut', 'cumstain', 'cunilingus', 'cunnilingus', 'cunt', 'cuntass', 'cuntbag',
  'cuntface', 'cunthole', 'cunthunter', 'cuntlick', 'cuntlicker', 'cuntlicking', 'cuntnugget',
  'cunts', 'cuntslut', 'cuntstruck', 'cuntsucker',
  'damn', 'dammit', 'damned', 'damnit', 'dick', 'dickbag', 'dickbeaters', 'dickbrain', 'dick Breath',
  'dickface', 'dickfarm', 'dickfuck', 'dickfucker', 'dickhead', 'dickheads', 'dickhole',
  'dickjockey', 'dicklick', 'dicklicker', 'dicknipples', 'dicknose', 'dickpipe', 'dickridder',
  'dickrider', 'dicks', 'dickskin', 'dickslap', 'dickstain', 'dickwad', 'dickweed', 'dickwhipper',
  'dickwod', 'dildo', 'dildos', 'dillweed', 'dingleberry', 'dipshit', 'dipshits', 'doggystyle',
  'douch', 'douche', 'douchebag', 'douchebags', 'douchewaffle', 'douchbag', 'dumbass', 'dumbasses',
  'dumbfuck', 'dunce', 'dyke', 'dykes',
  'ejaculate', 'ejaculated', 'ejaculates', 'ejaculating', 'ejaculation', 'enema', 'erection',
  'erotic', 'escort',
  'fag', 'fagbag', 'fagfucker', 'faggit', 'faggot', 'faggots', 'faggs', 'fagot', 'fags', 'fagtard',
  'fanny', 'fannybandit', 'fannyflaps', 'fannyfucker', 'fart', 'farted', 'fartface', 'farthead',
  'farting', 'farts', 'fcuk', 'felch', 'felcher', 'fellatio', 'feltch', 'fetish', 'fistfuck',
  'flamer', 'flange', 'fuck', 'fucked', 'fucker', 'fuckers', 'fuckface', 'fuckfest', 'fuckfest',
  'fuckhead', 'fuckheads', 'fuckhole', 'fuckin', 'fucking', 'fuckings', 'fuckme', 'fucknut',
  'fucknutt', 'fuckoff', 'fuckrod', 'fucks', 'fuckstick', 'fucktard', 'fucktart', 'fuckup',
  'fuckwad', 'fuckwhit', 'fuckwit', 'fuckwitt', 'fudgepacker',
  'gash', 'gay', 'gayass', 'gayboy', 'gaygirl', 'gays', 'gaywad', 'genital', 'genitals', 'gimp',
  'git', 'gobshite', 'goddam', 'goddamn', 'goddamned', 'goddamnit', 'golliwog', 'gonad', 'gonads',
  'gook', 'gooks',
  'halfwit', 'handjob', 'handjobs', 'hate', 'hentai', 'hitler', 'hobag', 'hoer', 'homo', 'homos',
  'homosexual', 'hooker', 'hookers', 'horny', 'hump', 'humping',
  'incest', 'injun',
  'jackass', 'jackasses', 'jackoff', 'jackoffs', 'jap', 'japs', 'jerk', 'jerkass', 'jerkface',
  'jerkoff', 'jesus', 'jizz', 'jizm', 'jizzum', 'jiz', 'junglebunny',
  'kafir', 'kike', 'kikes', 'kkk', 'knob', 'knobead', 'knobed', 'knobend', 'knobhead',
  'knobjockey', 'knobrot', 'knobweed', 'knobjocky', 'knobjocky',
  'labia', 'lardass', 'lesbian', 'lesbo', 'lez', 'lezbo', 'lezza', 'lezzie', 'lunatic', 'lust',
  'masterbate', 'masterbates', 'masterbating', 'masterbation', 'masturbate', 'masturbates',
  'masturbating', 'masturbation', 'milf', 'minge', 'minger', 'molest', 'molester', 'molestor',
  'mook', 'moron', 'motherfuck', 'motherfucker', 'motherfuckers', 'motherfucking', 'motherfuckka',
  'motherfuckkka', 'mtherfucker', 'muff', 'muffdiver', 'muffdiving', 'muffdiver', 'munter', 'nark',
  'naked', 'nazi', 'nazis', 'neegrow', 'negro', 'nig', 'nigga', 'niggah', 'niggaz', 'niggas',
  'nigger', 'niggers', 'nigguh', 'niglet', 'nigr', 'nimpho', 'nimphomania', 'nipple', 'nipples',
  'nips', 'nude', 'nudity', 'numpty', 'numpties',
  'oral', 'orgasm', 'orgasms', 'orgy', 'orgies',
  'paki', 'panties', 'panty', 'pedo', 'pedophile', 'pedophilia', 'penis', 'penises', 'penisfucker',
  'phuck', 'phuk', 'phuq', 'pimp', 'pimps', 'piss', 'pissed', 'pisser', 'pissers', 'pisses',
  'pissface', 'pissflaps', 'pisshead', 'pisshole', 'pissing', 'pisspig', 'pisspigs', 'pisspot',
  'pisswhore', 'pisswind', 'pillock', 'plonker', 'polack', 'polak', 'polesmoker', 'pollock',
  'poof', 'poon', 'poontang', 'porn', 'porno', 'pornography', 'pornhub', 'prick', 'pricks',
  'prig', 'prostitute', 'prostitution', 'pube', 'pubes', 'pubic', 'punani', 'punanny', 'punany',
  'punny', 'pussy', 'pussies', 'pussylicker', 'pussylicking', 'pussypounder', 'pussypounding',
  'pussysucker',
  'queef', 'queer', 'queers', 'quicky', 'quim',
  'raghead', 'rape', 'raped', 'raper', 'rapist', 'rapists', 'rectal', 'rectum', 'renob', 'retard',
  'retarded', 'retards', 'rim', 'rimjob', 'rimjobs', 'rough', 'ruski',
  'sadism', 'sadist', 'sadistic', 'sagg', 'scag', 'scank', 'schizo', 'schlong', 'scissoring',
  'scrote', 'scrotum', 'scum', 'semen', 'sex', 'sexy', 'sexual', 'sexually', 'shag', 'shagged',
  'shagger', 'shaggin', 'shagging', 'shat', 'shav', 'shemale', 'shit', 'shitass', 'shitbag',
  'shitbagger', 'shitblimp', 'shitbrain', 'shitbreath', 'shitcanned', 'shitclog', 'shitdick',
  'shitdump', 'shitface', 'shitfaced', 'shitfest', 'shitfuck', 'shithead', 'shitheads', 'shithole',
  'shithouse', 'shitter', 'shittiest', 'shitting', 'shitt', 'shitty', 'shitz', 'shiz', 'shiznit',
  'skag', 'skank', 'skanky', 'skankfuck', 'slag', 'sleaze', 'sleazeball', 'slut', 'sluts',
  'slutty', 'slutwhore', 'smeg', 'smegma', 'smutt', 'snatch', 'sod', 'sodom', 'sodomise',
  'sodomize', 'sodomy', 'spacker', 'spastic', 'spaz', 'spazmoid', 'spearchucker', 'sperm',
  'sperminator', 'spermjacker', 'spermwhale', 'spic', 'spick', 'spicks', 'spik', 'spiks',
  'splooge', 'spooge', 'spunk', 'stoned', 'stripclub', 'stripper', 'stupid', 'suck', 'sucks',
  'suckass', 'sucker',
  'tard', 'testes', 'testical', 'testicle', 'testicles', 'thundercunt', 'tim', 'tit', 'tits',
  'titt', 'titty', 'titties', 'tittie', 'tosser', 'tramp', 'trannie', 'tranny', 'transexual',
  'transsexual', 'trollop', 'tubgirl', 'turd', 'turds', 'twat', 'twathead', 'twatting',
  'twatwaffle', 'twazzock', 'twatface',
  'ugly', 'unclefucker', 'undies', 'unflushable', 'urinal', 'urine', 'urethra',
  'vag', 'vagina', 'vaginal', 'vajayjay', 'vibrator', 'vulva',
  'wad', 'wang', 'wank', 'wanked', 'wanker', 'wankers', 'wankfest', 'wankhole', 'wankiest',
  'wanking', 'wankjob', 'wankstain', 'wanksta', 'wankster', 'waz', 'wedgie', 'weed', 'whore',
  'whorebag', 'whoreface', 'whorefucker', 'whores', 'whorehouse', 'whoreish', 'whorelike',
  'whorish', 'wog', 'wombat', 'wop', 'wtf',
  'xrated', 'xxx',
  'yeasty', 'yid', 'yids',
  'zigabo', 'zigabos', 'zipperfish', 'zoophile', 'zoophilia'
];

const profanityFilter = (req, res, next) => {
  if (req.body.text) {
    const lowerText = req.body.text.toLowerCase();
    const found = badWords.some(word => {
      const regex = new RegExp('\\b' + word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b', 'i');
      return regex.test(lowerText);
    });
    if (found) {
      return res.status(400).json({ error: 'Your confession contains inappropriate language. Please revise.' });
    }
  }
  next();
};

module.exports = profanityFilter;
